### ISSUE TITLE
Infografía hilos

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/infografia-de-hilos-Blanca-estela-valerio-rivero#2]
[Infografía de las Caracteristicas y Aplicaciones de los hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Blanca-estela-valerio-rivero/files/15045554/Infografia.de.las.Caracteristicas.y.Aplicaciones.de.los.hilos.pdf)

**Comment by AmeliReyesHernandez** [comment]
20% de acuerdo a la rubrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
